name: Run Streamlit App

on:
  workflow_dispatch:

jobs:
  run-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run streamlit_app.py
        run: |
          python streamlit_app.py
